apiVersion: v1
kind: Service
metadata:
  name: ivaluate-public
  namespace: ivaluate
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: ivaluate-web
  ports:
    - name: http
      port: 80
      targetPort: 3000

